DROP TABLE IF EXISTS PRICES;
DROP TABLE IF EXISTS BRANDS;

CREATE TABLE BRANDS (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE PRICES (
    ID BIGSERIAL PRIMARY KEY,
    PRICE_LIST BIGINT NOT NULL,
    BRAND_ID BIGINT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRIORITY BIGINT NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    CURR VARCHAR(5) NOT NULL,
    CONSTRAINT FK_PRICES_BRAND
        FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(ID)
);